# This is a basic workflow to help you get started with Actions

name: CI
#Creating global environment variables
env:
  projectname: mule-project-1
  application_name: mule-project-1

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the feature branch
  push:
    branches: [ feature ]
  pull_request:
    branches: [ feature ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      pompath: ${{ env.projectname }}/pom.xml
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Checking Cache
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles(env.pompath) }}
          restore-keys: |
            ${{ runner.os }}-maven-
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          echo ${{ hashFiles('mule-project-1/pom.xml') }}
          echo mule-project-1/pom.xml
          echo **/pom.xml
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
